### ISSUE TITLE
Envoi commande python hex OK

### ISSUE THREAD

**Issue by patricklambotte** [FiReBlUe45/VOO-Evasion-API#1]
Bonjour, merci pour le travail effectué!  Je l'ai intégré moyennement a mon jeedom. Pourriez vous m'expliquer comment arrivez vous a recuperer les trames hexadécimales? car pour l'instant je n'ai que le controle du volume et du ch+ et -

Merci

**Comment by alamata** [comment]
bonjour,... 

tout d'abord un énorme merci à FiReBlUe45 !!!  pour son travail et ses recherches....

decimal to hex  -->>https://www.binaryhexconverter.com/decimal-to-hex-converter
hex to decimal  -->>https://www.binaryhexconverter.com/hex-to-decimal-converter
 and,...
python library  box      -->https://github.com/OrangeTux/einder

..;))

**Comment by patricklambotte** [comment]
super, merci je n'avais pas fait le rapprochement que c'était du décimal, merci pour le script

**Comment by FiReBlUe45** [comment]
Si vous avez des exemples de scripts ou des plugins, vous pouvez les ajouter au repo ;)
