### ISSUE TITLE
Voo Tv +

### ISSUE THREAD

**Issue by Razorjack74** [FiReBlUe45/VOO-Evasion-API#3]
Api ne fonctionne plus error connexion refused.   Auriez-vous une idée à mon avis le port à changé.

**Comment by FiReBlUe45** [comment]
Je n'ai pas encore testé avec la nouvelle version de la box, je vais y regarder cette semaine :)

**Comment by Razorjack74** [comment]
Un grand merci, j'ai posé la question sur le forum Voo mais pas de solution :-(  Sauf peut-être que les ports utilisés on changé car même en utilisant le paramètre -f il trouve plus la Box ....   En tout cas un grand merci car votre script python aidait une personne malvoyante pour changer les chaines par la voix.  Qui maintenant n'est plus possible .....

**Comment by FiReBlUe45** [comment]
Je viens d'y jetter un coup d'oeil, VOO a changé le système ... donc c'est un peu plus compliqué que juste un port.

Le nouveau système semble plus simple :)

Il vous faut un code en python ou autre chose pour votre outil? Vous utilisez quoi par curiosité?

**Comment by Razorjack74** [comment]
Simple j'utilise votre code python derrière domoticz tout simplement qui est relié à homebridge qui lui gère sans problème Google Home.

J'ai crée un interrupteur par chaine (Bouton poussoir) avec votre script et une variable selon le numéro de chaine et je lui ai donné le nom de la chaine qui est reconnu par Homebridge.

Votre code était parfait pour moi pq?  Vous avez d'autres idées?

**Comment by FiReBlUe45** [comment]
Car j'ai peu de temps pour refaire le script, demain je vais lister les code de chaque bouton. L'api de la box evasion est plus simple, elle utilise un call http avec un body avec le code. Je ne connais pas trop Domoticz, mais il existe peut etre la possibilité de créer des boutons avec le code à envoyer et ne plus avoir besoin du script python

**Comment by Razorjack74** [comment]
Merci pour votre proposition mais si c'était possible de garder la même idée que votre script dans un premier temps car domoticz n'est qu'une plateforme ou l'on peut attacher ce que l'on veut comme script qui tourne sous linux.  Donc dans mon cas le plus simple est votre code qui tourne sans problème et je vous en remercie.   Mais un call (même CURL ou autre) http avec python et le code du bouton peut-être suffisant pour ma part.    Je suis déjà très heureux que vous cherchiez la solution.

**Comment by Razorjack74** [comment]
Maintenant si ça peut simplifier les choses effectivement un call http avec le code du bouton si c'est plus simple pour vous je suis preneur :-)

**Comment by FiReBlUe45** [comment]
Je  n'ai pas encore fait le mapping des touches pour le moment j'ai power 0-9 vol + vol - mais j'ai adapté le script Python pouvez vous tester voir le bon fonctionnement?

Je'ai pas fini le mode pour trouver la box donc c'est à vous de trouver l'ip pour le moment.

**Comment by Razorjack74** [comment]
Bonjour merci pour le boulot désolé je viens de voir votre boulot je vais tester ce soir.  L'adresse ip je l'ai pas de soucis

**Comment by Razorjack74** [comment]
SUPER je viens de faire un test avec la branche dev et j'ai testé entre deux chaines à la main ça tourne nickel.  Un grand merci.

**Comment by Razorjack74** [comment]
Je suivrai pour mettre à jour lors de votre mise à jour final.

**Comment by Vincent-Stragier** [comment]
Bonjour @Razorjack74 et @FiReBlUe45,

Je viens de fortement retravailler mon code (https://github.com/2010019970909/VOO-Evasion-API/tree/master/evasion_API_Python3) pour le script evasion.py.  Je peux faire une nouvelle PR vers ce repo en cas de besoin. Je n'ai pas installé VOO TV+ sur ma box (pas intéressant) donc je ne peux pas garantir que ça fonctionne, mais je me suis inspiré des changements présents dans la branche "dev" de ce repo.

J'ai aussi décompilé l'APK de l'application Android VOO TV+ et j'ai trouvé quelques commandes manquantes (elles sont dans le JSON dans la clef `voo tv+`).

Le principal changement dans les commandes, c'est qu'il faut ajouter `-rfb` si l'on souhaite utiliser l'ancien mode de fonctionnement. On peut éventuellement ajouter `-http` dans les commandes, mais c'est le comportement par défaut.

N'hésitez pas à m'apporter des retours s'il y a des soucis au niveau du script [`evasion.py`](https://github.com/2010019970909/VOO-Evasion-API/tree/master/evasion_API_Python3).

Bon amusement,
Bien à vous,
Vincent

Edit. : par simplicité, je viens de publier le package sur [PyPI](https://pypi.org/project/voo-evasion/). Il suffit d'installer le module python (`py -3 -m pip install voo_evasion` sur Windows ou `python3 -m pip install voo_evasion` sur UNIX). Par la suite, il suffit d'utiliser `py -3 -m voo_evasion ...` ou `python3 -m voo_evasion ...` à la place du script (`py -3 evasion.py ...`).

**Comment by Razorjack74** [comment]
Bonjour @FiReBlUe45 

Un grand merci pour votre message, je vais y regarder quand j'aurai un peu de temps.
